# Generated by Django 3.2 on 2023-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('F', 'Free')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
