# Generated by Django 3.2 on 2023-04-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230426_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='progress',
            field=models.CharField(choices=[('1', 'Theory'), ('2', 'Obstacle'), ('3', 'Road')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
