# Generated by Django 3.2 on 2023-04-17 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField()),
                ('max_candidates', models.PositiveSmallIntegerField()),
                ('candidates', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
