# Generated by Django 3.2 on 2023-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdate',
            name='test_type',
            field=models.CharField(choices=[('WR', 'Written'), ('OB', 'Obstacle'), ('RD', 'Road')], default='WR', max_length=2),
            preserve_default=False,
        ),
    ]
