# Generated by Django 3.2 on 2023-04-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_dates', '0003_auto_20230425_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testapplication',
            old_name='test_application',
            new_name='application_status',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='application',
        ),
    ]
