# Generated by Django 3.2 on 2023-04-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dates', '0004_auto_20230425_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='test_type',
            field=models.CharField(choices=[('1', 'Theory'), ('2', 'Obstacle'), ('3', 'Road')], max_length=2),
        ),
    ]
