# Generated by Django 3.2 on 2023-04-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dates', '0005_alter_testdate_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='test_type',
            field=models.CharField(choices=[('WR', 'Written'), ('OB', 'Obstacle'), ('RD', 'Road')], max_length=2),
        ),
    ]
