# Generated by Django 3.2 on 2023-04-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_dates', '0008_auto_20230426_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_dates.testapplication'),
        ),
    ]
